repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.1
    hooks:
      - id: prettier
  - repo: https://github.com/gitguardian/gg-shield
    rev: v1.17.3
    hooks:
      - id: ggshield
        language_version: python3
        stages: [commit]
