import 'angular'
import 'angular-sanitize'
import 'angular-animate'
import 'angular-aria'
import 'angular-messages'
import '@uirouter/angularjs'
import 'moment'
import 'api-check'
import 'angular-formly'
import 'angular-formly-templates-bootstrap'
import 'angular-ui-bootstrap'
import 'angular-chips/dist/angular-chips.min.js'
import 'angular-tablesort'
import 'ng-flow/dist/ng-flow-standalone.min.js'
import 'angular-file-saver'

import '/app/frontend/js/app.js'
import '/app/frontend/js/routing.extra.js'

import '/rapydo/src/ng1/common.jsonapi.parser.js'
import '/rapydo/src/ng1/common.data.service.js'
import '/rapydo/src/ng1/common.ngflow.controller.js'
import '/rapydo/src/ng1/common.sessions.js'
import '/rapydo/src/ng1/common.formly.service.js'
import '/rapydo/src/ng1/common.users.js'
import '/rapydo/src/ng1/admin.users.controller.js'
import '/rapydo/src/ng1/common.noty.js'
import '/rapydo/src/ng1/common.filters.js'
import '/rapydo/src/ng1/common.lists.controller.js'
import '/rapydo/src/ng1/common.config.js'
import '/rapydo/src/ng1/common.form_dialogs.js'
/*import '/rapydo/src/ng1/common.api.js'*/

import '/rapydo/src/ng1/common.routes.js'
/*import '/rapydo/src/ng1/common.auth.js'*/
import '/rapydo/src/ng1/main.controller.js'

import '/rapydo/src/css/framework.css'
import '/rapydo/src/css/material.icons.css'

import 'bootstrap3/css/bootstrap.min.css'
import 'bootstrap3/css/bootstrap-theme.min.css'
import 'noty/lib/noty.css'
import 'noty/lib/themes/relax.css'
import 'noty/lib/themes/metroui.css'
import 'font-awesome/css/font-awesome.min.css'
// Search all palette-
import 'google-material-color/dist/palette.css'
import 'angular-chips/dist/main.css'
import 'angular-tablesort/tablesort.css'
