import 'jquery'
import 'angular'
import 'angular-sanitize'
import 'angular-animate'
import 'angular-aria'
import 'angular-messages'
import '@uirouter/angularjs'
import 'satellizer'
import 'noty'
import 'moment'
import 'angular-hotkeys'
import 'api-check'
import 'angular-formly'
import 'angular-formly-templates-bootstrap'
import 'angular-ui-bootstrap'
// import 'angular-ui-bootstrap/dist/ui-bootstrap.js'
// import 'angular-ui-bootstrap/dist/ui-bootstrap-tpls.js'
// import 'angular-chips'
import 'angular-tablesort'
// import 'ng-flow'
import 'angular-file-saver'

import '/app/frontend/js/app.js'
import '/rapydo/src/ng1/common.jsonapi.parser.js'
import '/rapydo/src/ng1/common.data.service.js'
import '/rapydo/src/ng1/common.ngflow.controller.js'
import '/rapydo/src/ng1/common.sessions.js'
import '/rapydo/src/ng1/common.formly.service.js'
import '/rapydo/src/ng1/common.users.js'
import '/rapydo/src/ng1/admin.users.controller.js'
// import '/rapydo/src/ng1/common.globals.js'
import '/rapydo/src/ng1/common.noty.js'
import '/rapydo/src/ng1/common.filters.js'
import '/rapydo/src/ng1/common.lists.controller.js'
import '/rapydo/src/ng1/common.config.js'
import '/rapydo/src/ng1/common.form_dialogs.js'
import '/rapydo/src/ng1/common.api.js'
import '/rapydo/src/ng1/common.routes.js'
import '/rapydo/src/ng1/common.auth.js'
import '/rapydo/src/ng1/main.controller.js'

import '/app/frontend/js/routing.extra.js'
import '/app/frontend/js/data.service.js'
import '/app/frontend/js/stage.controller.js'

import '/rapydo/src/css/framework.css'
import '/rapydo/src/css/material.icons.css'

import '/rapydo/src/ng1/start.js'


// angular-hotkeys/build/hotkeys.min.css'
import 'bootstrap/dist/css/bootstrap.min.css'
import 'bootstrap/dist/css/bootstrap-theme.min.css'
// noty/lib/noty.css'
// noty/lib/themes/relax.css'
// noty/lib/themes/metroui.css'

// Search all palette-
import 'google-material-color/dist/palette.css'

// angular-chips/dist/main.css'
// angular-tablesort/tablesort.css'
