name: Karma

on:
  push:
  pull_request:
  workflow_dispatch:

# Cancel previous running jobs on the same branch in case of new pushs
concurrency:
  group: karma-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "16.x"
      - name: Install
        env:
          REF_BRANCH: ${{ github.ref }}
          HEAD_REF_BRANCH: ${{ github.head_ref }}

        run: |
          python -m pip install --upgrade pip
          # version is "x.y.0": convert in x.y
          export CURRENT_VERSION=$(grep '"version"' src/package.json | awk {'print $2'} | tr -d '", ' | awk -F. {'print $1 "." $2'})
          pip install --upgrade --no-cache-dir git+https://github.com/rapydo/do.git@${CURRENT_VERSION}
          mkdir rapydo_tests
          cd rapydo_tests
          rapydo install compose
          rapydo --testing create prj --auth neo4j --frontend angular --origin-url https://your_remote_git/your_project.git

          # REF contains the branch when commit, but contains refs/pull/XXX/merge on PRs
          # with PRs use HEAD_REF
          # Strip out refs/heads/ prefix
          if [[ ! -z $HEAD_REF_BRANCH ]];
          then
            BRANCH=${HEAD_REF_BRANCH/refs\/heads\//}
          else
            BRANCH=${REF_BRANCH/refs\/heads\//}
          fi
          # Also strip out tags from the branch
          BRANCH=${BRANCH/refs\/tags\/v/}
          echo "Forcing rapydo-angular to branch ${BRANCH}"
          echo "  submodules:" >> projects/prj/project_configuration.yaml
          echo "    rapydo-angular:" >> projects/prj/project_configuration.yaml
          echo "      branch: \"${BRANCH}\"" >> projects/prj/project_configuration.yaml

          # This is to create a commit in the history to fill the BUILD variable
          git config --global user.email "tests@rapy.do"
          git config --global user.name "RAPyDo"
          git add -A && git commit -a -m "Initial commit"

      - name: Run Karma
        run: |
          cd rapydo_tests
          rapydo --testing init
          rapydo pull --quiet frontend
          rapydo start frontend
          sleep 5
          rapydo shell frontend "yarn install"
          rapydo shell frontend "yarn workspaces focus --all"
          rapydo shell frontend "reload-types"
          rapydo shell frontend "yarn info --recursive --dependents"
          rapydo shell frontend "yarn run test:single"

      - name: Coverage
        uses: rapydo/actions/coverage@v2
        with:
          repository: rapydo_tests/submodules/rapydo-angular
          cov_file: rapydo_tests/data/prj/karma/lcov.info

      - name: Docker logs on failure
        if: failure()
        run: |
          cd rapydo_tests
          rapydo logs
